# SPDX-License-Identifier: Apache-2.0
"""Platform-native wrapper script generator for west-env.

Generates lightweight wrapper scripts that proxy to `west env <action>`.

  Windows  → .ps1 PowerShell scripts (no Bash, no WSL, no wsl.exe)
  Linux    → .sh shell scripts
  macOS    → .sh shell scripts

All wrappers:
  - Forward all arguments to the underlying west env action.
  - Exit with the same exit code as west.
  - Use the same action name so documentation applies equally on all platforms.
"""

import stat
import sys
from pathlib import Path
from typing import List


# Actions for which wrappers are generated
ACTIONS = [
    "setup",
    "sync",
    "build",
    "flash",
    "debug",
    "cache",
    "benchmark",
    "doctor",
    "generate-tasks",
]


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_PS1_TEMPLATE = """\
#Requires -Version 5.1
# west-env wrapper: west env {action}
# Generated by west-env. Do not edit.
# Runs natively in PowerShell. No Linux subsystem or remote extensions required.
param([Parameter(ValueFromRemainingArguments)]$PassThrough)
$ErrorActionPreference = 'Stop'
& west env {action} @PassThrough
exit $LASTEXITCODE
"""

_SH_TEMPLATE = """\
#!/bin/sh
# west-env wrapper: west env {action}
# Generated by west-env. Do not edit.
set -e
exec west env {action} "$@"
"""


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


def get_extension(host_platform: str = None) -> str:
    """Return the wrapper script extension for the given platform."""
    plat = host_platform or sys.platform
    return ".ps1" if plat == "win32" else ".sh"


def generate_wrapper_content(action: str, host_platform: str = None) -> str:
    """Return the text content of a wrapper script for *action*."""
    plat = host_platform or sys.platform
    template = _PS1_TEMPLATE if plat == "win32" else _SH_TEMPLATE
    return template.format(action=action)


def generate_wrappers(
    scripts_dir: Path,
    actions: List[str] = None,
    host_platform: str = None,
) -> List[Path]:
    """Generate wrapper scripts in *scripts_dir*.

    Args:
        scripts_dir:   Directory to write scripts into (created if absent).
        actions:       List of action names. Defaults to ACTIONS.
        host_platform: Override sys.platform.

    Returns:
        List of Path objects of created scripts.
    """
    plat = host_platform or sys.platform
    ext = get_extension(plat)
    scripts_dir = Path(scripts_dir)
    scripts_dir.mkdir(parents=True, exist_ok=True)

    created = []
    for action in actions or ACTIONS:
        filename = f"west-env-{action}{ext}"
        path = scripts_dir / filename
        content = generate_wrapper_content(action, plat)
        path.write_text(content, encoding="utf-8")

        # Make executable on POSIX
        if plat != "win32":
            current = path.stat().st_mode
            path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

        created.append(path)

    return created


def doctor_lines(scripts_dir: Path = None, host_platform: str = None) -> list:
    """Return doctor output lines for platform wrapper status."""
    plat = host_platform or sys.platform
    ext = get_extension(plat)
    lines = [f"Platform: {plat}  wrapper extension: {ext}"]

    if scripts_dir is None:
        lines.append("[INFO] scripts_dir not set — run `west env generate-tasks` to create wrappers")
        return lines

    scripts_dir = Path(scripts_dir)
    for action in ACTIONS:
        fname = f"west-env-{action}{ext}"
        path = scripts_dir / fname
        if path.is_file():
            lines.append(f"[PASS] wrapper: {fname}")
        else:
            lines.append(f"[WARN] wrapper missing: {fname}  — run `west env generate-tasks`")

    return lines
